// default package
// Generated 19 ene 2021 3:30:01 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ApplicationHasQuestion generated by hbm2java
 */
@Entity
@Table(name = "application_has_question", catalog = "encuesta")
public class ApplicationHasQuestion implements java.io.Serializable {

	private Integer id;
	private Application application;
	private Question question;
	private String applicationHasQuestionvalue;

	public ApplicationHasQuestion() {
	}

	public ApplicationHasQuestion(Application application, Question question) {
		this.application = application;
		this.question = question;
	}

	public ApplicationHasQuestion(Application application, Question question, String applicationHasQuestionvalue) {
		this.application = application;
		this.question = question;
		this.applicationHasQuestionvalue = applicationHasQuestionvalue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "application_idapplication", nullable = false)
	public Application getApplication() {
		return this.application;
	}

	public void setApplication(Application application) {
		this.application = application;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "question_QuestionID", nullable = false)
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@Column(name = "application_has_questionvalue", length = 45)
	public String getApplicationHasQuestionvalue() {
		return this.applicationHasQuestionvalue;
	}

	public void setApplicationHasQuestionvalue(String applicationHasQuestionvalue) {
		this.applicationHasQuestionvalue = applicationHasQuestionvalue;
	}

}
