// default package
// Generated 28 dic 2020 19:50:55 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol", catalog = "encuesta")
public class Rol implements java.io.Serializable {

	private Integer rolId;
	private String rolNombre;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Rol() {
	}

	public Rol(String rolNombre) {
		this.rolNombre = rolNombre;
	}

	public Rol(String rolNombre, Set<Usuario> usuarios) {
		this.rolNombre = rolNombre;
		this.usuarios = usuarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RolID", unique = true, nullable = false)
	public Integer getRolId() {
		return this.rolId;
	}

	public void setRolId(Integer rolId) {
		this.rolId = rolId;
	}

	@Column(name = "RolNombre", nullable = false, length = 45)
	public String getRolNombre() {
		return this.rolNombre;
	}

	public void setRolNombre(String rolNombre) {
		this.rolNombre = rolNombre;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "usuario_has_rol", catalog = "encuesta", joinColumns = {
			@JoinColumn(name = "rol_RolID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Usuario_UsuarioID", nullable = false, updatable = false) })
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
