// default package
// Generated 19 ene 2021 3:30:01 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Segmentation generated by hbm2java
 */
@Entity
@Table(name = "segmentation", catalog = "encuesta", uniqueConstraints = @UniqueConstraint(columnNames = "segmentationName"))
public class Segmentation implements java.io.Serializable {

	private Integer segmentationId;
	private Survey survey;
	private String segmentationName;
	private Set<Segmentationitem> segmentationitems = new HashSet<Segmentationitem>(0);

	public Segmentation() {
	}

	public Segmentation(Survey survey, String segmentationName) {
		this.survey = survey;
		this.segmentationName = segmentationName;
	}

	public Segmentation(Survey survey, String segmentationName, Set<Segmentationitem> segmentationitems) {
		this.survey = survey;
		this.segmentationName = segmentationName;
		this.segmentationitems = segmentationitems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "segmentationID", unique = true, nullable = false)
	public Integer getSegmentationId() {
		return this.segmentationId;
	}

	public void setSegmentationId(Integer segmentationId) {
		this.segmentationId = segmentationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "survey_SurveyID", nullable = false)
	public Survey getSurvey() {
		return this.survey;
	}

	public void setSurvey(Survey survey) {
		this.survey = survey;
	}

	@Column(name = "segmentationName", unique = true, nullable = false, length = 45)
	public String getSegmentationName() {
		return this.segmentationName;
	}

	public void setSegmentationName(String segmentationName) {
		this.segmentationName = segmentationName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "segmentation")
	public Set<Segmentationitem> getSegmentationitems() {
		return this.segmentationitems;
	}

	public void setSegmentationitems(Set<Segmentationitem> segmentationitems) {
		this.segmentationitems = segmentationitems;
	}

}
