// default package
// Generated 28 dic 2020 19:50:55 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Segmentationitem generated by hbm2java
 */
@Entity
@Table(name = "segmentationitem", catalog = "encuesta")
public class Segmentationitem implements java.io.Serializable {

	private Integer segmentationitemId;
	private Segmentation segmentation;
	private String segmentationitemName;
	private Set<Application> applications = new HashSet<Application>(0);

	public Segmentationitem() {
	}

	public Segmentationitem(Segmentation segmentation, String segmentationitemName) {
		this.segmentation = segmentation;
		this.segmentationitemName = segmentationitemName;
	}

	public Segmentationitem(Segmentation segmentation, String segmentationitemName, Set<Application> applications) {
		this.segmentation = segmentation;
		this.segmentationitemName = segmentationitemName;
		this.applications = applications;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "segmentationitemID", unique = true, nullable = false)
	public Integer getSegmentationitemId() {
		return this.segmentationitemId;
	}

	public void setSegmentationitemId(Integer segmentationitemId) {
		this.segmentationitemId = segmentationitemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "segmentation_segmentationID", nullable = false)
	public Segmentation getSegmentation() {
		return this.segmentation;
	}

	public void setSegmentation(Segmentation segmentation) {
		this.segmentation = segmentation;
	}

	@Column(name = "segmentationitemName", nullable = false, length = 45)
	public String getSegmentationitemName() {
		return this.segmentationitemName;
	}

	public void setSegmentationitemName(String segmentationitemName) {
		this.segmentationitemName = segmentationitemName;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "application_has_segmentationitem", catalog = "encuesta", joinColumns = {
			@JoinColumn(name = "segmentationitem_segmentationitemID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "application_idapplication", nullable = false, updatable = false) })
	public Set<Application> getApplications() {
		return this.applications;
	}

	public void setApplications(Set<Application> applications) {
		this.applications = applications;
	}

}
