// default package
// Generated 21 oct 2020 17:29:49 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Segmentation generated by hbm2java
 */
@Entity
@Table(name = "segmentation", catalog = "encuesta", uniqueConstraints = @UniqueConstraint(columnNames = "segmentationName"))
public class Segmentation implements java.io.Serializable {

	private int segmentationId;
	private String segmentationName;
	private Set<Survey> surveys = new HashSet<Survey>(0);
	private Set<Segmentationitem> segmentationitems = new HashSet<Segmentationitem>(0);

	public Segmentation() {
	}

	public Segmentation(int segmentationId, String segmentationName) {
		this.segmentationId = segmentationId;
		this.segmentationName = segmentationName;
	}

	public Segmentation(int segmentationId, String segmentationName, Set<Survey> surveys,
			Set<Segmentationitem> segmentationitems) {
		this.segmentationId = segmentationId;
		this.segmentationName = segmentationName;
		this.surveys = surveys;
		this.segmentationitems = segmentationitems;
	}

	@Id

	@Column(name = "segmentationID", unique = true, nullable = false)
	public int getSegmentationId() {
		return this.segmentationId;
	}

	public void setSegmentationId(int segmentationId) {
		this.segmentationId = segmentationId;
	}

	@Column(name = "segmentationName", unique = true, nullable = false, length = 45)
	public String getSegmentationName() {
		return this.segmentationName;
	}

	public void setSegmentationName(String segmentationName) {
		this.segmentationName = segmentationName;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "survey_has_segmentation", catalog = "encuesta", joinColumns = {
			@JoinColumn(name = "segmentation_segmentationID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "survey_SurveyID", nullable = false, updatable = false) })
	public Set<Survey> getSurveys() {
		return this.surveys;
	}

	public void setSurveys(Set<Survey> surveys) {
		this.surveys = surveys;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "segmentation")
	public Set<Segmentationitem> getSegmentationitems() {
		return this.segmentationitems;
	}

	public void setSegmentationitems(Set<Segmentationitem> segmentationitems) {
		this.segmentationitems = segmentationitems;
	}

}
