// default package
// Generated 19 oct 2020 21:12:21 by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * StatementAnalysis generated by hbm2java
 */
@Entity
@Table(name = "statement_analysis", catalog = "sys")
public class StatementAnalysis implements java.io.Serializable {

	private StatementAnalysisId id;

	public StatementAnalysis() {
	}

	public StatementAnalysis(StatementAnalysisId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "query", column = @Column(name = "query")),
			@AttributeOverride(name = "db", column = @Column(name = "db", length = 64)),
			@AttributeOverride(name = "fullScan", column = @Column(name = "full_scan", nullable = false, length = 1)),
			@AttributeOverride(name = "execCount", column = @Column(name = "exec_count", nullable = false)),
			@AttributeOverride(name = "errCount", column = @Column(name = "err_count", nullable = false)),
			@AttributeOverride(name = "warnCount", column = @Column(name = "warn_count", nullable = false)),
			@AttributeOverride(name = "totalLatency", column = @Column(name = "total_latency", length = 65535)),
			@AttributeOverride(name = "maxLatency", column = @Column(name = "max_latency", length = 65535)),
			@AttributeOverride(name = "avgLatency", column = @Column(name = "avg_latency", length = 65535)),
			@AttributeOverride(name = "lockLatency", column = @Column(name = "lock_latency", length = 65535)),
			@AttributeOverride(name = "rowsSent", column = @Column(name = "rows_sent", nullable = false)),
			@AttributeOverride(name = "rowsSentAvg", column = @Column(name = "rows_sent_avg", nullable = false, precision = 21, scale = 0)),
			@AttributeOverride(name = "rowsExamined", column = @Column(name = "rows_examined", nullable = false)),
			@AttributeOverride(name = "rowsExaminedAvg", column = @Column(name = "rows_examined_avg", nullable = false, precision = 21, scale = 0)),
			@AttributeOverride(name = "rowsAffected", column = @Column(name = "rows_affected", nullable = false)),
			@AttributeOverride(name = "rowsAffectedAvg", column = @Column(name = "rows_affected_avg", nullable = false, precision = 21, scale = 0)),
			@AttributeOverride(name = "tmpTables", column = @Column(name = "tmp_tables", nullable = false)),
			@AttributeOverride(name = "tmpDiskTables", column = @Column(name = "tmp_disk_tables", nullable = false)),
			@AttributeOverride(name = "rowsSorted", column = @Column(name = "rows_sorted", nullable = false)),
			@AttributeOverride(name = "sortMergePasses", column = @Column(name = "sort_merge_passes", nullable = false)),
			@AttributeOverride(name = "digest", column = @Column(name = "digest", length = 64)),
			@AttributeOverride(name = "firstSeen", column = @Column(name = "first_seen", nullable = false, length = 26)),
			@AttributeOverride(name = "lastSeen", column = @Column(name = "last_seen", nullable = false, length = 26)) })
	public StatementAnalysisId getId() {
		return this.id;
	}

	public void setId(StatementAnalysisId id) {
		this.id = id;
	}

}
