// default package
// Generated 19 oct 2020 21:12:21 by Hibernate Tools 5.1.10.Final


import X.hostSummaryByFileIoId;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * X.hostSummaryByFileIo generated by hbm2java
 */
@Entity
@Table(name="x$host_summary_by_file_io"
    ,catalog="sys"
)
public class X.hostSummaryByFileIo  implements java.io.Serializable {


     private X.hostSummaryByFileIoId id;

    public X.hostSummaryByFileIo() {
    }

    public X.hostSummaryByFileIo(X.hostSummaryByFileIoId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="host", column=@Column(name="host") ), 
        @AttributeOverride(name="ios", column=@Column(name="ios", precision=42, scale=0) ), 
        @AttributeOverride(name="ioLatency", column=@Column(name="io_latency", precision=42, scale=0) ) } )
    public X.hostSummaryByFileIoId getId() {
        return this.id;
    }
    
    public void setId(X.hostSummaryByFileIoId id) {
        this.id = id;
    }




}


