// default package
// Generated 19 oct 2020 21:12:21 by Hibernate Tools 5.1.10.Final


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * X.memoryGlobalTotal generated by hbm2java
 */
@Entity
@Table(name="x$memory_global_total"
    ,catalog="sys"
)
public class X.memoryGlobalTotal  implements java.io.Serializable {


     private BigDecimal totalAllocated;

    public X.memoryGlobalTotal() {
    }

    public X.memoryGlobalTotal(BigDecimal totalAllocated) {
       this.totalAllocated = totalAllocated;
    }
   
     @Id 

    
    @Column(name="total_allocated", precision=41, scale=0)
    public BigDecimal getTotalAllocated() {
        return this.totalAllocated;
    }
    
    public void setTotalAllocated(BigDecimal totalAllocated) {
        this.totalAllocated = totalAllocated;
    }




}


