package com.example.demo.survey.dominio;

// default package
// Generated 23 sep 2020 14:24:34 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.example.demo.util.dominio.Views;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonView;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * Segmentation generated by hbm2java
 */
@Entity
@Table(name = "segmentation", catalog = "encuesta", uniqueConstraints = @UniqueConstraint(columnNames = "segmentationName"))
public class Segmentation implements java.io.Serializable {

	@JsonView(Views.User.class)
	private int segmentationId;
	@JsonView(Views.User.class)
	private String segmentationName;
	@JsonView(Views.User.class)
	private Set<Segmentationitem> segmentationitems = new HashSet<Segmentationitem>(0);

	public Segmentation() {
	}

	public Segmentation(int segmentationId, String segmentationName) {
		this.segmentationId = segmentationId;
		this.segmentationName = segmentationName;
	}

	public Segmentation(int segmentationId, String segmentationName, Set<Segmentationitem> segmentationitems) {
		this.segmentationId = segmentationId;
		this.segmentationName = segmentationName;
		this.segmentationitems = segmentationitems;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "segmentationID", unique = true, nullable = false)
	public int getSegmentationId() {
		return this.segmentationId;
	}

	public void setSegmentationId(int segmentationId) {
		this.segmentationId = segmentationId;
	}

	@Column(name = "segmentationName", unique = true, nullable = false, length = 45)
	public String getSegmentationName() {
		return this.segmentationName;
	}

	public void setSegmentationName(String segmentationName) {
		this.segmentationName = segmentationName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "segmentation")
	public Set<Segmentationitem> getSegmentationitems() {
		return this.segmentationitems;
	}

	public void setSegmentationitems(Set<Segmentationitem> segmentationitems) {
		this.segmentationitems = segmentationitems;
	}

}
