package com.example.demo.survey.dominio;

import java.util.HashSet;
import java.util.Set;

// default package
// Generated 23 sep 2020 14:24:34 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.example.demo.survey.dominio.dtos.SegmentationitemNewSurveyDto;
import com.example.demo.surveyparticipant.dominio.Application;
import com.example.demo.surveyparticipant.dominio.Surveyparticipant;
import com.example.demo.util.dominio.Views;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonView;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * Segmentationitem generated by hbm2java
 */
@Entity
@Table(name = "segmentationitem", catalog = "encuesta")
public class Segmentationitem implements java.io.Serializable {

	private int segmentationitemId;

	private Segmentation segmentation;

	private String segmentationitemName;

	public Segmentationitem() {
		super();
	}

	public Segmentationitem(int segmentationitemId, Segmentation segmentation, String segmentationitemName) {
		this.segmentationitemId = segmentationitemId;
		this.segmentation = segmentation;
		this.segmentationitemName = segmentationitemName;
	}

	public Segmentationitem(SegmentationitemNewSurveyDto tempp) {
		this.segmentationitemName = tempp.getSegmentationitemName();
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "segmentationitemID", unique = true, nullable = false)
	public int getSegmentationitemId() {
		return this.segmentationitemId;
	}

	public void setSegmentationitemId(int segmentationitemId) {
		this.segmentationitemId = segmentationitemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "segmentation_segmentationID", insertable = false, updatable = false, nullable = false)
	public Segmentation getSegmentation() {
		return this.segmentation;
	}

	public void setSegmentation(Segmentation segmentation) {
		this.segmentation = segmentation;
	}

	@Column(name = "segmentationitemName", nullable = false, length = 45)
	public String getSegmentationitemName() {
		return this.segmentationitemName;
	}

	public void setSegmentationitemName(String segmentationitemName) {
		this.segmentationitemName = segmentationitemName;
	}

}
