package com.example.demo.category.domino;

// default package
// Generated 21 sep 2020 7:34:12 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import java.util.stream.Collectors;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.example.demo.category.domino.dtos.CategoryNewSurveyDto;
import com.example.demo.question.dominio.Question;
import com.example.demo.survey.dominio.Survey;
import com.example.demo.util.dominio.Views;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonView;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "encuesta")
public class Category implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "CategoryID", nullable = false)
	private Long categoryId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "survey_SurveyID", insertable = false, updatable = false, nullable = false)
	private Survey survey;

	@Column(name = "CategoryName", nullable = false, length = 45)
	private String categoryName;

	@OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "category_CategoryID", nullable = false)
	private Set<Question> questions = new HashSet<Question>(0);

	public Category() {
		super();
	}

	public Category(Survey survey, String categoryName) {
		this.survey = survey;
		this.categoryName = categoryName;
	}

	public Category(Survey survey, String categoryName, Set<Question> questions) {
		this.survey = survey;
		this.categoryName = categoryName;
		this.questions = questions;
	}

	public Category(CategoryNewSurveyDto temp) {
		super();
		this.categoryId=temp.getCategoryId();
		this.categoryName = temp.getCategoryName();
		this.questions = temp.getQuestions().stream().map(tempp -> {
			Question p = new Question(tempp);
			return p;
		}).collect(Collectors.toSet());

	}

	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	public Survey getSurvey() {
		return this.survey;
	}

	public void setSurvey(Survey survey) {
		this.survey = survey;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

}
