package com.example.demo.surveyparticipantanswer.dominio;

// default package
// Generated 19 oct 2020 20:39:44 by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;
import javax.persistence.Table;

import com.example.demo.question.dominio.Question;
import com.example.demo.surveyparticipant.dominio.Application;
import com.example.demo.util.dominio.Views;
import com.fasterxml.jackson.annotation.JsonView;

/**
 * ApplicationHasQuestion generated by hbm2java
 */
@Entity
@Table(name = "application_has_question", catalog = "encuesta")
public class ApplicationHasQuestion implements java.io.Serializable {

	@JsonView(Views.User.class)
	private int applicationhasquestionid;
	private Application application;
	@JsonView(Views.User.class)
	private Question question;
	@JsonView(Views.User.class)
	private String applicationHasQuestionvalue;

	public ApplicationHasQuestion() {
	}

	public ApplicationHasQuestion(int applicationhasquestionid, Application application, Question question) {
		this.applicationhasquestionid = applicationhasquestionid;
		this.application = application;
		this.question = question;
	}

	public ApplicationHasQuestion(int applicationhasquestionid, Application application, Question question,
			String applicationHasQuestionvalue) {
		this.applicationhasquestionid = applicationhasquestionid;
		this.application = application;
		this.question = question;
		this.applicationHasQuestionvalue = applicationHasQuestionvalue;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "applicationhasquestionid", unique = true, nullable = false)
	public int getId() {
		return this.applicationhasquestionid;
	}

	public void setId(int applicationhasquestionid) {
		this.applicationhasquestionid = applicationhasquestionid;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "application_idapplication", insertable = false, updatable = false, nullable = false)
	public Application getApplication() {
		return this.application;
	}

	public void setApplication(Application application) {
		this.application = application;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "question_QuestionID", nullable = false)
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@Column(name = "application_has_questionvalue", length = 45)
	public String getApplicationHasQuestionvalue() {
		return this.applicationHasQuestionvalue;
	}

	public void setApplicationHasQuestionvalue(String applicationHasQuestionvalue) {
		this.applicationHasQuestionvalue = applicationHasQuestionvalue;
	}

}